export const URL = "https://api.currencybeacon.com/v1/timeseries";
export const API_KEY = "y9Lr8Jt6aK3be0TtboYtqS81JCM002kw";
export const BASE_CURRENCY = "try";

export const getToday = () => {
  const today = new Date();
  return today.toISOString().split('T')[0]; // Форматируем дату в формат yyyy-mm-dd
}

export const getWeekAgo = () => {
  const weekAgo = new Date();
  weekAgo.setDate(weekAgo.getDate() - 7);
  return weekAgo.toISOString().split('T')[0]; // Форматируем дату в формат yyyy-mm-dd
}

export const getCurrencySymbol = (currencyCode) => {
  switch (currencyCode) {
      case "USD":
          return "$";
      case "UAH":
          return "₴";
      case "EUR":
          return "€";
      case "GBP":
          return "£";
      case "JPY":
          return "¥";
      case "CNY":
          return "¥";
      case "RUB":
          return "₽";
      case "ILS":
          return "₪";
      case "INR":
          return "₨";
      case "KRW":
          return "₩";
      case "NGN":
          return "₦";
      case "THB":
          return "฿";
      case "VND":
          return "₫";
      case "LAK":
          return "₭";
      case "KHR":
          return "៛";
      case "MNT":
          return "₮";
      case "PHP":
          return "₱";
      case "IRR":
          return "﷼";
      case "CRC":
          return "₡";
      case "PYG":
          return "₲";
      case "AFN":
          return "؋";
      case "GHS":
          return "₵";
      case "KZT":
          return "₸";
      case "TRY":
          return "₺";
      case "AZN":
          return "₼";
      case "GEL":
          return "₾";
      case "PLN":
          return "Zł";
      case "ESP":
          return "₧";
      case "FRF":
          return "₣";
      case "ITL":
          return "₤";
      case "NLG":
          return "ƒ";
      case "GRD":
          return "₯";
      case "BRZ":
          return "₢";
      case "ARA":
          return "₳";
      case "BOB":
          return "\$b";
      case "KPW":
          return "₩";
      case "ANG":
          return "ƒ";
      case "PAB":
          return "B/.";
      case "MGA":
          return "Ar";
      case "VEF":
          return "BsF";
      case "ETB":
          return "Br";
      case "VUV":
          return "Vt";
      case "DZD":
          return "دج";
      case "BHD":
          return ".د.ب";
      case "JOD":
          return ".د.إ";
      case "IQD":
          return "ع.د";
      case "KWD":
          return "د.ك";
      case "LYD":
          return "ل.د";
      case "RSD":
          return "Din";
      case "TND":
          return "د.ت";
      case "MAD":
          return "د.م";
      case "AED":
          return "د.إ";
      case "STN":
          return "nDb";
      case "AUD":
          return "\$";
      case "BSD":
          return "B\$";
      case "BZD":
          return "BZ\$";
      case "BMD":
          return "BD\$";
      case "BND":
          return "B\$";
      case "XCD":
          return "EC\$";
      case "GYD":
          return "GY\$";
      case "HKD":
          return "HK\$";
      case "ZWD":
          return "Z\$";
      case "KYD":
          return "$";
      case "CAD":
          return "CA\$";
      case "LRD":
          return "L\$";
      case "NAD":
          return "N\$";
      case "NZD":
          return "$";
      case "SGD":
          return "S\$";
      case "SBD":
          return "SI\$";
      case "SRD":
          return "$";
      case "TWD":
          return "NT\$";
      case "TTD":
          return "TT\$";
      case "FJD":
          return "FJ\$";
      case "JMD":
          return "FJ\$";
      case "AMD":
          return "դր.";
      case "GTQ":
          return "Q";
      case "PGK":
          return "K";
      case "NIO":
          return "C\$";
      case "DKK":
          return "kr";
      case "ISK":
          return "kr";
      case "NOK":
          return "kr";
      case "CZK":
          return "Kč";
      case "SEK":
          return "kr";
      case "HRK":
          return "Kn";
      case "MMK":
          return "K";
      case "LVL":
          return "Ls";
      case "BGN":
          return "лв";
      case "MDL":
          return "L";
      case "RON":
          return "Lei";
      case "ALL":
          return "Lek";
      case "HNL":
          return "L.";
      case "SLL":
          return "Le";
      case "SZL":
          return "E";
      case "LTL":
          return "Lt";
      case "LSL":
          return "L";
      case "TMТ":
          return "m";
      case "BAM":
          return "КМ";
      case "MZN":
          return "MT";
      case "ERN":
          return "Nfk";
      case "BTN":
          return "Nu";
      case "TOP":
          return "T\$";
      case "MOP":
          return "MOP\$";
      case "ARS":
          return "$";
      case "DOP":
          return "RD\$";
      case "COP":
          return "$";
      case "CUP":
          return "\$MN";
      case "MXN":
          return "$";
      case "UYU":
          return "\$U";
      case "CLP":
          return "$";
      case "BWP":
          return "P";
      case "BRL":
          return "R\$";
      case "YER":
          return "﷼";
      case "QAR":
          return "﷼";
      case "OMR":
          return "﷼";
      case "MYR":
          return "RM";
      case "SAR":
          return "﷼";
      case "BYR":
          return "Br";
      case "BYN":
          return "Br";
      case "IDR":
          return "Rp";
      case "MUR":
          return "₨";
      case "NPR":
          return "Rs";
      case "PKR":
          return "Rs";
      case "SCR":
          return "SR";
      case "LKR":
          return "Rs";
      case "MVR":
          return "Rf";
      case "ZAR":
          return "R";
      case "PEN":
          return "S/";
      case "KGS":
          return "сом";
      case "TJS":
          return "смн";
      case "UZS":
          return "so’m";
      case "BDT":
          return "৳";
      case "WST":
          return "WS\$";
      case "MRO":
          return "UM";
      case "AWG":
          return "ƒ";
      case "HUF":
          return "ƒ";
      case "BIF":
          return "FBu";
      case "GNF":
          return "FG";
      case "DJF":
          return "Fdj";
      case "KMF":
          return "₣";
      case "CDF":
          return "FC";
      case "RWF":
          return "RF";
      case "CHF":
          return "sFr";
      case "XPF":
          return "F";
      case "XOF":
          return "CFA";
      case "XAF":
          return "CFA";
      case "GIP":
          return "£";
      case "EGP":
          return "£";
      case "LBP":
          return "£";
      case "SHP":
          return "£";
      case "SYP":
          return "£";
      case "SDG":
          return "£";
      case "FKP":
          return "£";
      case "KES":
          return "KSh";
      case "SOS":
          return "So";
      case "TZS":
          return "TSh";
      case "UGX":
          return "USh";
      case "CVE":
          return "$";
      case "SRG":
          return "ƒ";
      case "SVC":
          return "₡";
      case "SKK":
          return "Sk";
      case "CSJ":
          return "CSJ";
      case "EEK":
          return "EEK";
      case "MTL":
          return "£";
      case "DEM":
          return "DM";
      case "FIM":
          return "mk";
      case "BOP":
          return "B\$";
      case "ECS":
          return "ECS";
      case "SIT":
          return "SIT";
      case "BEF":
          return "BF";
      case "LUF":
          return "F";
      case "IEP":
          return "IR£";
      case "CYP":
          return "£";
      case "ATS":
          return "öS";
      case "TPE":
          return "$ ";
      case "PTE":
          return "$ ";
      case "BTC":
          return "₿";
      case "XBT":
          return "₿";
      case "ETH":
          return "Ξ";
      case "LTC":
          return "Ł";
      case "NMC":
          return "ℕ";
      case "XRP":
          return "XRP";
      case "QRK":
          return "QRK";
      case "NXT":
          return "NXT";
      case "AOA":
          return "Kz";
      case "ADA":
          return "₳";
      case "Lek":
          return "L";
      case "BBD":
          return "Bbd\$";
      case "CUC":
          return "\$MN";
      case "DOGE":
          return "Ð";
      case "GGP":
          return "£";
      case "GHC":
          return "₵";
      case "HTG":
          return "G";
      case "IMP":
          return "£";
      case "JEP":
          return "£";
      case "MGF":
          return "MFr";
      case "MKD":
          return "DEN";
      case "MRU":
          return "UM";
      case "MWK":
          return "MK";
      case "MXV":
          return "$";
      case "MZM":
          return "MT";
      case "ROL":
          return "lej";
      case "SDD":
          return "£Sd";
      case "SLE":
          return "Le";
      case "STD":
          return "nDb";
      case "TRL":
          return "₺";
      case "TVD":
          return "\$";
      case "VAL":
          return "L";
      case "VEB":
          return "BsF";
      case "VED":
          return "Bs";
      case "VES":
          return "Bs.";
      case "ZMK":
          return "ZK";
      case "ZMW":
          return "ZK";
      case "ZWL":
          return "Z\$";
      default:
          return "";
  }
};